expo -> react-native: works on Web with react-native-web; and
use cross-env to let most package.json scripts can run on Windows;

since DISABLE_ESLINT_PLUGIN=true in `npm run web` , then we can use any version of eslint, so use eslint@7 even can be used in nodejs 10

upgrade eslint from 6.5.1 to 7.8.1 to
fix ESLint `Error: Failed to load plugin 'flowtype' declared in '.eslintrc.js » @react-native-community/eslint-config#overrides[0]': Cannot find module 'eslint/use-at-your-own-risk'`

not upgrade eslint to ^8.4.1 to
fix ESLint `TypeError: Module.createRequire is not a function` when using nodejs v10.15.3